from required import Required
from requiredchars import RequiredChars
from length import Length
from matches import Matches
from numeric import Numeric
from integer import Integer
from natural import Natural
from email import Email
from phone import Phone
